/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pos.layered.view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pos.layered.controller.ItemController;
import javax.swing.table.DefaultTableModel;
import pos.layered.dto.ItemDto;

/**
 *
 * @author wmara
 */
public class ItemPanel extends javax.swing.JPanel {

	private ItemController itemController;

	/**
	 * Creates new form ItemPanel
	 */
	public ItemPanel() throws Exception {
		itemController = new ItemController();
		initComponents();
		loadAllItems();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                basePannel = new javax.swing.JPanel();
                headerPannel = new javax.swing.JPanel();
                headerLable = new javax.swing.JLabel();
                formPannel = new javax.swing.JPanel();
                custidLabel = new javax.swing.JLabel();
                itemCodeText = new javax.swing.JTextField();
                custTitleLabel = new javax.swing.JLabel();
                descriptionText = new javax.swing.JTextField();
                custDOBLabel = new javax.swing.JLabel();
                packSizeText = new javax.swing.JTextField();
                custCityLabel = new javax.swing.JLabel();
                unitPrizeText = new javax.swing.JTextField();
                custPostalLabel = new javax.swing.JLabel();
                qtyText = new javax.swing.JTextField();
                saveButton = new javax.swing.JButton();
                updateButton = new javax.swing.JButton();
                deleteButton = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                itemTable = new javax.swing.JTable();

                headerLable.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
                headerLable.setText("Manage Item");

                javax.swing.GroupLayout headerPannelLayout = new javax.swing.GroupLayout(headerPannel);
                headerPannel.setLayout(headerPannelLayout);
                headerPannelLayout.setHorizontalGroup(
                        headerPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerPannelLayout.createSequentialGroup()
                                .addComponent(headerLable, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );
                headerPannelLayout.setVerticalGroup(
                        headerPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerPannelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(headerLable, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                );

                custidLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                custidLabel.setText("Item Code");

                itemCodeText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

                custTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                custTitleLabel.setText("Description");

                descriptionText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

                custDOBLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                custDOBLabel.setText("Pack Size");

                packSizeText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

                custCityLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                custCityLabel.setText("Unit Price");

                unitPrizeText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

                custPostalLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                custPostalLabel.setText("Quantity On Hand");

                qtyText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

                saveButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                saveButton.setText("Save Item");
                saveButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                saveButtonActionPerformed(evt);
                        }
                });

                updateButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                updateButton.setText("Update Item");
                updateButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                updateButtonActionPerformed(evt);
                        }
                });

                deleteButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                deleteButton.setText("Delete Item");
                deleteButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                deleteButtonActionPerformed(evt);
                        }
                });

                itemTable.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                itemTable.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                itemTableMouseClicked(evt);
                        }
                });
                jScrollPane1.setViewportView(itemTable);

                javax.swing.GroupLayout formPannelLayout = new javax.swing.GroupLayout(formPannel);
                formPannel.setLayout(formPannelLayout);
                formPannelLayout.setHorizontalGroup(
                        formPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formPannelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(formPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(formPannelLayout.createSequentialGroup()
                                                .addGroup(formPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(custidLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(custTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(custDOBLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(formPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(itemCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(descriptionText, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(packSizeText, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(formPannelLayout.createSequentialGroup()
                                                .addComponent(custCityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(unitPrizeText, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(formPannelLayout.createSequentialGroup()
                                                .addComponent(custPostalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(qtyText, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formPannelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(updateButton)
                                .addGap(18, 18, 18)
                                .addComponent(saveButton)
                                .addGap(77, 77, 77))
                        .addGroup(formPannelLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
                                .addContainerGap())
                );
                formPannelLayout.setVerticalGroup(
                        formPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(formPannelLayout.createSequentialGroup()
                                .addGroup(formPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(custidLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(itemCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(formPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(custTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(descriptionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(formPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(custDOBLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(packSizeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(formPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(custCityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(unitPrizeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(formPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(custPostalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(qtyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(formPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(saveButton)
                                        .addComponent(updateButton)
                                        .addComponent(deleteButton))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(37, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout basePannelLayout = new javax.swing.GroupLayout(basePannel);
                basePannel.setLayout(basePannelLayout);
                basePannelLayout.setHorizontalGroup(
                        basePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(headerPannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(basePannelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(formPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                );
                basePannelLayout.setVerticalGroup(
                        basePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(basePannelLayout.createSequentialGroup()
                                .addComponent(headerPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(formPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(basePannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(basePannel, javax.swing.GroupLayout.PREFERRED_SIZE, 461, Short.MAX_VALUE)
                );
        }// </editor-fold>//GEN-END:initComponents

        private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
		saveItem();
        }//GEN-LAST:event_saveButtonActionPerformed

        private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
		updateItem();
        }//GEN-LAST:event_updateButtonActionPerformed

        private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
		deleteItem();
        }//GEN-LAST:event_deleteButtonActionPerformed

        private void itemTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemTableMouseClicked
		try {
			searchItem();
		} catch (Exception ex) {
			Logger.getLogger(ItemPanel.class.getName()).log(Level.SEVERE, null, ex);
		}
        }//GEN-LAST:event_itemTableMouseClicked


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel basePannel;
        private javax.swing.JLabel custCityLabel;
        private javax.swing.JLabel custDOBLabel;
        private javax.swing.JLabel custPostalLabel;
        private javax.swing.JLabel custTitleLabel;
        private javax.swing.JLabel custidLabel;
        private javax.swing.JButton deleteButton;
        private javax.swing.JTextField descriptionText;
        private javax.swing.JPanel formPannel;
        private javax.swing.JLabel headerLable;
        private javax.swing.JPanel headerPannel;
        private javax.swing.JTextField itemCodeText;
        private javax.swing.JTable itemTable;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTextField packSizeText;
        private javax.swing.JTextField qtyText;
        private javax.swing.JButton saveButton;
        private javax.swing.JTextField unitPrizeText;
        private javax.swing.JButton updateButton;
        // End of variables declaration//GEN-END:variables

	private void saveItem() {
		try {
			ItemDto itemDto = new ItemDto(itemCodeText.getText(),
				descriptionText.getText(),
				packSizeText.getText(),
				Double.parseDouble(unitPrizeText.getText()),
				Integer.parseInt(qtyText.getText()));

			String resp = itemController.addIdem(itemDto);
			JOptionPane.showMessageDialog(this, resp);
			clear();
			loadAllItems();

		} catch (Exception ex) {
			Logger.getLogger(ItemPanel.class.getName()).log(Level.SEVERE, null, ex);
			JOptionPane.showMessageDialog(this, ex.getMessage());
		}
	}

	private void updateItem() {
		try {
			ItemDto itemDto = new ItemDto(itemCodeText.getText(),
				descriptionText.getText(),
				packSizeText.getText(),
				Double.parseDouble(unitPrizeText.getText()),
				Integer.parseInt(qtyText.getText()));

			String resp = itemController.updateItem(itemDto);
			JOptionPane.showMessageDialog(this, resp);
			clear();
			loadAllItems();

		} catch (Exception ex) {
			Logger.getLogger(ItemPanel.class.getName()).log(Level.SEVERE, null, ex);
			JOptionPane.showMessageDialog(this, ex.getMessage());
		}
	}

	private void deleteItem() {
		try {
			String resp = itemController.deleteItem(itemCodeText.getText());
			JOptionPane.showMessageDialog(this, resp);
			clear();
			loadAllItems();

		} catch (Exception ex) {
			Logger.getLogger(ItemPanel.class.getName()).log(Level.SEVERE, null, ex);
			JOptionPane.showMessageDialog(this, ex.getMessage());
		}
	}

	private void searchItem() throws Exception {
		try {
			String itemCode = itemTable.getValueAt(itemTable.getSelectedRow(), 0).toString();

			ItemDto itemDto = itemController.getItem(itemCode);

			if (itemDto != null) {
				itemCodeText.setText(itemDto.getId());
				descriptionText.setText(itemDto.getDescription());
				packSizeText.setText(itemDto.getPackSize());
				unitPrizeText.setText(Double.toString(itemDto.getUnitPrice()));
				qtyText.setText(Integer.toString(itemDto.getQoh()));

			} else {
				JOptionPane.showMessageDialog(this, "Item Not Found");
			}
		} catch (Exception ex) {
			Logger.getLogger(ItemPanel.class.getName()).log(Level.SEVERE, null, ex);
			JOptionPane.showMessageDialog(this, ex.getMessage());
		}
	}

	private void loadAllItems() throws Exception {
		try {
			String[] collumns = {"Item Code", "Description", "Pack Size", "Unit Prize", "Qty"};
			DefaultTableModel dtm = new DefaultTableModel(collumns, 0) {
				@Override
				public boolean isCellEditable(int row, int column) {
					return false;
				}
			};
			itemTable.setModel(dtm);
			ArrayList<ItemDto> itemDtos = itemController.getAllItem();
			for (ItemDto item : itemDtos) {
				Object[] row = {item.getId(), item.getDescription(),
					item.getPackSize(), item.getUnitPrice(),
					item.getQoh()};
				dtm.addRow(row);

			}
		} catch (Exception ex) {
			Logger.getLogger(ItemPanel.class.getName()).log(Level.SEVERE, null, ex);
			JOptionPane.showMessageDialog(this, ex.getMessage());
		}
	}

	private void clear() {
		itemCodeText.setText("");
		descriptionText.setText("");
		packSizeText.setText("");
		unitPrizeText.setText("");
		qtyText.setText("");
	}
}
