/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pos.layered.view;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author wmara
 */
public class LayoutView extends javax.swing.JFrame {

	/**
	 * Creates new form LayoutView
	 */
	public LayoutView() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                headerPanel = new javax.swing.JPanel();
                headerLabel = new javax.swing.JLabel();
                sideNavPanel = new javax.swing.JPanel();
                manageItemButton = new javax.swing.JButton();
                manageCustomerButton1 = new javax.swing.JButton();
                bodyPanel = new javax.swing.JPanel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                headerPanel.setBackground(new java.awt.Color(153, 153, 153));

                headerLabel.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
                headerLabel.setForeground(new java.awt.Color(0, 0, 0));
                headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                headerLabel.setText("SuperMarket");

                javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
                headerPanel.setLayout(headerPanelLayout);
                headerPanelLayout.setHorizontalGroup(
                        headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(headerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
                );
                headerPanelLayout.setVerticalGroup(
                        headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerPanelLayout.createSequentialGroup()
                                .addComponent(headerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                .addContainerGap())
                );

                sideNavPanel.setBackground(new java.awt.Color(153, 153, 255));

                manageItemButton.setBackground(new java.awt.Color(204, 204, 204));
                manageItemButton.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
                manageItemButton.setForeground(new java.awt.Color(0, 0, 0));
                manageItemButton.setText("Manage Item");
                manageItemButton.setActionCommand("Manage Item");
                manageItemButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                manageItemButtonActionPerformed(evt);
                        }
                });

                manageCustomerButton1.setBackground(new java.awt.Color(204, 204, 204));
                manageCustomerButton1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
                manageCustomerButton1.setForeground(new java.awt.Color(0, 0, 0));
                manageCustomerButton1.setText("Manage Customer");
                manageCustomerButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                manageCustomerButton1ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout sideNavPanelLayout = new javax.swing.GroupLayout(sideNavPanel);
                sideNavPanel.setLayout(sideNavPanelLayout);
                sideNavPanelLayout.setHorizontalGroup(
                        sideNavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideNavPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(manageItemButton, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(sideNavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(sideNavPanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(manageCustomerButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap()))
                );
                sideNavPanelLayout.setVerticalGroup(
                        sideNavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sideNavPanelLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(manageItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(366, Short.MAX_VALUE))
                        .addGroup(sideNavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(sideNavPanelLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(manageCustomerButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(414, Short.MAX_VALUE)))
                );

                javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
                bodyPanel.setLayout(bodyPanelLayout);
                bodyPanelLayout.setHorizontalGroup(
                        bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );
                bodyPanelLayout.setVerticalGroup(
                        bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(sideNavPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sideNavPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void manageItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageItemButtonActionPerformed
		try {
			loadItemPanel();
		} catch (Exception ex) {
			Logger.getLogger(LayoutView.class.getName()).log(Level.SEVERE, null, ex);
		}
        }//GEN-LAST:event_manageItemButtonActionPerformed

        private void manageCustomerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCustomerButton1ActionPerformed
		loadCustomerManage();
        }//GEN-LAST:event_manageCustomerButton1ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(LayoutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(LayoutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(LayoutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(LayoutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new LayoutView().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel bodyPanel;
        private javax.swing.JLabel headerLabel;
        private javax.swing.JPanel headerPanel;
        private javax.swing.JButton manageCustomerButton1;
        private javax.swing.JButton manageItemButton;
        private javax.swing.JPanel sideNavPanel;
        // End of variables declaration//GEN-END:variables

	private void loadCustomerManage() {
		bodyPanel.removeAll();
		CustomerPanel customerPannel = new CustomerPanel();
		customerPannel.setSize(bodyPanel.getWidth(), bodyPanel.getHeight());
		bodyPanel.add(customerPannel);
		bodyPanel.repaint();
		bodyPanel.revalidate();

	}

	private void loadItemPanel() throws Exception {
		bodyPanel.removeAll();
		ItemPanel itemPannel = new ItemPanel();
		itemPannel.setSize(bodyPanel.getWidth(), bodyPanel.getHeight());
		bodyPanel.add(itemPannel);
		bodyPanel.repaint();
		bodyPanel.revalidate();
	}
}
