/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pos.layered.view;

import java.awt.List;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pos.layered.controller.CustomerController;
import pos.layered.controller.ItemController;
import pos.layered.controller.OrderController;
import pos.layered.dto.CustomerDto;
import pos.layered.dto.ItemDto;
import pos.layered.dto.OrderDetailDto;
import pos.layered.dto.OrderDto;

/**
 *
 * @author wmara
 */
public class OrderPanel extends javax.swing.JPanel {

	private ArrayList<OrderDetailDto> orderDetailDto = new ArrayList<>();

	private CustomerController customerController;
	private ItemController itemController;
	private OrderController orderController;

	/**
	 * Creates new form OrderPanel
	 */
	public OrderPanel() {
		customerController = new CustomerController();
		itemController = new ItemController();
		orderController = new OrderController();
		initComponents();
		loadTable();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                basePannel = new javax.swing.JPanel();
                headerPannel = new javax.swing.JPanel();
                headerLable = new javax.swing.JLabel();
                formPannel = new javax.swing.JPanel();
                orderIdLabel = new javax.swing.JLabel();
                orderIDText = new javax.swing.JTextField();
                custIDLabel = new javax.swing.JLabel();
                custIDText = new javax.swing.JTextField();
                searchCustButt = new javax.swing.JButton();
                custSearchLabel = new javax.swing.JLabel();
                jSeparator1 = new javax.swing.JSeparator();
                itemCodeLabel = new javax.swing.JLabel();
                itemIDText = new javax.swing.JTextField();
                qtyLabel = new javax.swing.JLabel();
                qtyText = new javax.swing.JTextField();
                addItemButt = new javax.swing.JButton();
                itemSearchLabel = new javax.swing.JLabel();
                searchItemtButt = new javax.swing.JButton();
                discountLabel = new javax.swing.JLabel();
                discountText = new javax.swing.JTextField();
                jScrollPane1 = new javax.swing.JScrollPane();
                itemTable = new javax.swing.JTable();
                placeOrderButt = new javax.swing.JButton();
                tablePannel = new javax.swing.JPanel();

                headerLable.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
                headerLable.setText("Order");

                javax.swing.GroupLayout headerPannelLayout = new javax.swing.GroupLayout(headerPannel);
                headerPannel.setLayout(headerPannelLayout);
                headerPannelLayout.setHorizontalGroup(
                        headerPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(headerLable, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                );
                headerPannelLayout.setVerticalGroup(
                        headerPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerPannelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(headerLable, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                );

                orderIdLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                orderIdLabel.setText("Order ID");

                orderIDText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

                custIDLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                custIDLabel.setText("Customer ID");

                custIDText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

                searchCustButt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                searchCustButt.setText("Search");
                searchCustButt.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                searchCustButtActionPerformed(evt);
                        }
                });

                itemCodeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                itemCodeLabel.setText("Item Code");

                itemIDText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

                qtyLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                qtyLabel.setText("Qty");

                qtyText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

                addItemButt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                addItemButt.setText("Add Item");
                addItemButt.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                addItemButtActionPerformed(evt);
                        }
                });

                searchItemtButt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                searchItemtButt.setText("Search");
                searchItemtButt.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                searchItemtButtActionPerformed(evt);
                        }
                });

                discountLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                discountLabel.setText("Discount");

                discountText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

                itemTable.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                jScrollPane1.setViewportView(itemTable);

                placeOrderButt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                placeOrderButt.setText("Place Order");
                placeOrderButt.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                placeOrderButtActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout formPannelLayout = new javax.swing.GroupLayout(formPannel);
                formPannel.setLayout(formPannelLayout);
                formPannelLayout.setHorizontalGroup(
                        formPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(formPannelLayout.createSequentialGroup()
                                .addGroup(formPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator1)
                                        .addGroup(formPannelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(formPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(formPannelLayout.createSequentialGroup()
                                                                .addGroup(formPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(orderIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(custIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(formPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(orderIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(formPannelLayout.createSequentialGroup()
                                                                                .addComponent(custIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(29, 29, 29)
                                                                                .addComponent(searchCustButt)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(custSearchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                                .addGap(230, 230, 230))
                                                        .addGroup(formPannelLayout.createSequentialGroup()
                                                                .addGroup(formPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(formPannelLayout.createSequentialGroup()
                                                                                .addComponent(itemCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(itemIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(formPannelLayout.createSequentialGroup()
                                                                                .addComponent(qtyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(qtyText, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGroup(formPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(formPannelLayout.createSequentialGroup()
                                                                                .addGap(28, 28, 28)
                                                                                .addComponent(searchItemtButt)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(itemSearchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addGap(231, 231, 231))
                                                                        .addGroup(formPannelLayout.createSequentialGroup()
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(discountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(discountText, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(addItemButt)
                                                                                .addGap(0, 53, Short.MAX_VALUE)))))))
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formPannelLayout.createSequentialGroup()
                                .addGroup(formPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formPannelLayout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(placeOrderButt)
                                                .addGap(38, 38, 38)))
                                .addGap(35, 35, 35))
                );
                formPannelLayout.setVerticalGroup(
                        formPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(formPannelLayout.createSequentialGroup()
                                .addGroup(formPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(orderIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(orderIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(formPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(custIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(custIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(searchCustButt)
                                        .addComponent(custSearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(formPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(itemCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(itemIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(itemSearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(searchItemtButt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(formPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(formPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(qtyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(qtyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(formPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(discountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(discountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(addItemButt)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(placeOrderButt)
                                .addGap(23, 23, 23))
                );

                javax.swing.GroupLayout tablePannelLayout = new javax.swing.GroupLayout(tablePannel);
                tablePannel.setLayout(tablePannelLayout);
                tablePannelLayout.setHorizontalGroup(
                        tablePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );
                tablePannelLayout.setVerticalGroup(
                        tablePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );

                javax.swing.GroupLayout basePannelLayout = new javax.swing.GroupLayout(basePannel);
                basePannel.setLayout(basePannelLayout);
                basePannelLayout.setHorizontalGroup(
                        basePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tablePannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(basePannelLayout.createSequentialGroup()
                                .addComponent(headerPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(basePannelLayout.createSequentialGroup()
                                .addComponent(formPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );
                basePannelLayout.setVerticalGroup(
                        basePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(basePannelLayout.createSequentialGroup()
                                .addComponent(headerPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(formPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(194, 194, 194)
                                .addComponent(tablePannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(basePannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(basePannel, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                );
        }// </editor-fold>//GEN-END:initComponents

        private void searchCustButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCustButtActionPerformed
		searchCustomer();
        }//GEN-LAST:event_searchCustButtActionPerformed

        private void addItemButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemButtActionPerformed
		addToTable();
        }//GEN-LAST:event_addItemButtActionPerformed

        private void searchItemtButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchItemtButtActionPerformed
		searchItem();
        }//GEN-LAST:event_searchItemtButtActionPerformed

        private void placeOrderButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderButtActionPerformed
		placeOrder();
        }//GEN-LAST:event_placeOrderButtActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton addItemButt;
        private javax.swing.JPanel basePannel;
        private javax.swing.JLabel custIDLabel;
        private javax.swing.JTextField custIDText;
        private javax.swing.JLabel custSearchLabel;
        private javax.swing.JLabel discountLabel;
        private javax.swing.JTextField discountText;
        private javax.swing.JPanel formPannel;
        private javax.swing.JLabel headerLable;
        private javax.swing.JPanel headerPannel;
        private javax.swing.JLabel itemCodeLabel;
        private javax.swing.JTextField itemIDText;
        private javax.swing.JLabel itemSearchLabel;
        private javax.swing.JTable itemTable;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JTextField orderIDText;
        private javax.swing.JLabel orderIdLabel;
        private javax.swing.JButton placeOrderButt;
        private javax.swing.JLabel qtyLabel;
        private javax.swing.JTextField qtyText;
        private javax.swing.JButton searchCustButt;
        private javax.swing.JButton searchItemtButt;
        private javax.swing.JPanel tablePannel;
        // End of variables declaration//GEN-END:variables

	private void loadTable() {
		String[] collumns = {"Item Code", "Qty", "Discount"};
		DefaultTableModel dtm = new DefaultTableModel(collumns, 0) {
			@Override
			public boolean isCellEditable(int row, int column) {
				return false;
			}
		};
		itemTable.setModel(dtm);
	}

	private void searchCustomer() {
		try {
			String custID = custIDText.getText();
			CustomerDto cust = customerController.getCustomer(custID);
			if (cust != null) {
				custSearchLabel.setText(cust.getName() + "," + cust.getAddress());
			} else {
				JOptionPane.showMessageDialog(this, "Customer Not Found");
			}
		} catch (Exception ex) {
			Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
			JOptionPane.showMessageDialog(this, ex.getMessage());
		}
	}

	private void searchItem() {
		try {
			String itemID = itemIDText.getText();
			ItemDto item = itemController.getItem(itemID);
			if (item != null) {
				itemSearchLabel.setText(item.getDescription() + "," + item.getUnitPrice() + "," + item.getQoh());
			} else {
				JOptionPane.showMessageDialog(this, "Item Not Found");
			}
		} catch (Exception ex) {
			Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	private void addToTable() {
		OrderDetailDto od = new OrderDetailDto(itemIDText.getText(),Integer.parseInt(qtyText.getText()),
			Double.parseDouble(discountText.getText()));
		orderDetailDto.add(od);

		Object[] rowdata = {od.getItemId(), od.getQty(), od.getDiscount()};

		DefaultTableModel dtm = (DefaultTableModel) itemTable.getModel();
		dtm.addRow(rowdata);
		cleanItemData();
	}

	private void cleanItemData() {
		itemIDText.setText("");
		discountText.setText("");
		qtyText.setText("");
		searchItemtButt.setText("");
	}

	private void placeOrder() {
		try{
		OrderDto orderDto = new OrderDto(orderIDText.getText(),
			custIDText.getText(), orderDetailDto);
		
		String result = orderController.placeOrder(orderDto);
		JOptionPane.showMessageDialog(this, result);
            
        } catch (Exception ex) {
            Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
			
	}
}
